usd_path: limx_hu_d03.usd
morphology_group: humanoid
base_body_name: base_link
foot_body_names: contact_foot_heel_L|contact_foot_heel_R
action_scale: 0.5
actuator_stiffness: 120.0
actuator_damping: 2.4
