usd_path: unitree_h1_2.usd
morphology_group: humanoid
base_body_name: pelvis
foot_body_names: left_ankle_roll_link|right_ankle_roll_link
action_scale: 0.5
actuator_stiffness: 200.0
actuator_damping: 4.0
