usd_path: xiaopeng_px5.usd
base_body_name: base_link
foot_body_names: ll5_l|rl5_l
actuator:
  type: simple
  stiffness: 120.0
  damping: 2.4
action:
  type: position_only
  scale: 0.5
rewards:
- name: track_lin_vel_xy_exp
  weight: 1.0
- name: track_ang_vel_z_exp
  weight: 0.5
- name: ang_vel_xy_l2
  weight: -0.05
- name: dof_torques_l2
  weight: -1.0e-05
- name: dof_acc_l2
  weight: -2.5e-07
- name: action_rate_l2
  weight: -0.01
- name: flat_orientation_l2
  weight: -1.0
- name: dof_pos_limits
  weight: -1.0
- name: termination_penalty
  weight: -200.0
- name: feet_air_time_biped
  weight: 0.25
  params:
    threshold: 0.4
- name: feet_slide
  weight: -0.25
termination:
- contact
policy_architecture: mlp
algorithm: ppo
domain_randomization: basic
agent:
  num_envs: 4096
  max_iterations: 3000
  learning_rate: 0.001
  entropy_coef: 0.01
  hidden_dims:
  - 512
  - 256
  - 128
