usd_path: unitree_go1.usd
morphology_group: quadruped
base_body_name: base
foot_body_names: FL_foot|FR_foot|RL_foot|RR_foot
action_scale: 0.25
default_joint_pos:
  FL_hip_joint: 0.1
  RL_hip_joint: 0.1
  FR_hip_joint: -0.1
  RR_hip_joint: -0.1
  FL_thigh_joint: 0.8
  FR_thigh_joint: 0.8
  RL_thigh_joint: 1.0
  RR_thigh_joint: 1.0
  FL_calf_joint: -1.5
  FR_calf_joint: -1.5
  RL_calf_joint: -1.5
  RR_calf_joint: -1.5
undesired_contact_body_names: FL_calf|FR_calf|RL_calf|RR_calf
actuator_stiffness: 25.0
actuator_damping: 0.5
