usd_path: unitree_a1.usd
morphology_group: quadruped
base_body_name: base
foot_body_names: FL_foot|FR_foot|RL_foot|RR_foot
action_scale: 0.5
undesired_contact_body_names: FL_calf|FR_calf|RL_calf|RR_calf
default_joint_pos:
  FL_calf_joint: -103.49999
  FR_calf_joint: -103.49999
  RL_calf_joint: -103.49999
  RR_calf_joint: -103.49999
actuator_stiffness: 33.5
actuator_damping: 0.67
